/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./frame2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FrameModel_2(props) {
  const { nodes, materials } = useGLTF('/model/frame2.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/model/frame2.glb')
