/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./frame1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FrameModel_1(props) {
  const { nodes, materials } = useGLTF('/model/frame1.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/model/frame1.glb')
